/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Ventana_Princ;
import Modelo.Calculadora;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class PrincipalCalculadora extends javax.swing.JFrame {

    private Controlador_Ventana_Princ controlador_Ventana_Princ;

    /**
     * Creates new form calcu
     */
    public PrincipalCalculadora() {
        initComponents();
        controlador_Ventana_Princ = new Controlador_Ventana_Princ(this);
        this.jBCalcular.addActionListener(controlador_Ventana_Princ);
        //this.jTImprecion.addActionListener(controlador_Ventana_Princ);
        jTImprecion.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTImprecion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTEntrada = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CALCULAORA");

        jLabel2.setText("Operacion");

        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTImprecion, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel1)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTImprecion, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBCalcular)
                    .addComponent(jTEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCalculadora().setVisible(true);
            }
        });
    }

    public String getJtEntrada() {
        return this.jTEntrada.getText();
    }

    public void setJtEntrada(String jtEntrada) {
        this.jTEntrada.setText(jtEntrada);
    }

    public String getJtImprecion() {
        return this.jTImprecion.toString();
    }

    public void setJtImprecion(String jTImprecion) {
        this.jTImprecion.setText(jTImprecion);
    }

    public void calcuOpe() {

        Calculadora calculadora = new Calculadora();

        Pattern patronSuma = Pattern.compile("(\\d+)\\+(\\d+)");

        Pattern patronResta = Pattern.compile("(\\d+)\\-(\\d+)");
        Pattern patronDivision = Pattern.compile("(\\d+)\\/(\\d+)");
        Pattern patronMultiplicacion = Pattern.compile("(\\d+)\\*(\\d+)");
        Pattern patronIgualdad = Pattern.compile("=");
        Matcher matcher = patronSuma.matcher(getJtEntrada());

        int resultado = 0;
        double numero1 = 0;
        double numero2 = 0;

        //  Este es el proceso para la suma
        matcher = patronSuma.matcher(getJtEntrada());
        while (matcher.find()) {
            numero1 = Integer.parseInt(matcher.group(1));
            numero2 = Integer.parseInt(matcher.group(2));
            resultado += numero1 + numero2;
        }
        // Este es el proceso para la resta
        matcher = patronResta.matcher(getJtEntrada());
        while (matcher.find()) {
            numero1 = Integer.parseInt(matcher.group(1));
            numero2 = Integer.parseInt(matcher.group(2));
            resultado += numero1 - numero2;
        }
        // Este es el proceso para la division
        matcher = patronDivision.matcher(getJtEntrada());
        while (matcher.find()) {
            numero1 = Integer.parseInt(matcher.group(1));
            numero2 = Integer.parseInt(matcher.group(2));
            resultado += numero1 / numero2;
        }
// Este es el proceso para la Multiplicacion
        matcher = patronMultiplicacion.matcher(getJtEntrada());
        while (matcher.find()) {
            numero1 = Integer.parseInt(matcher.group(1));
            numero2 = Integer.parseInt(matcher.group(2));
            resultado += numero1 * numero2;
        }
        // Este es el proceso para la igualdad
        matcher = patronIgualdad.matcher(getJtEntrada());
        if (matcher.find()) {
            //JOptionPane.showMessageDialog(this, "El Resultado de la operacion es " + resultado);
            jTImprecion.setText(String.valueOf("El resultado es: " + resultado));
        } else {
            JOptionPane.showMessageDialog(this, "Debe de ingresar el simbolo de igual");

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTEntrada;
    private javax.swing.JTextField jTImprecion;
    // End of variables declaration//GEN-END:variables
}
